FIX: Fix missing wxTimerEvent declaration
In file included from /run/build/BambuStudio/src/slic3r/GUI/FilamentGroupPopup.cpp:1:
/run/build/BambuStudio/src/slic3r/GUI/FilamentGroupPopup.hpp:33:18: error: ‘wxTimerEvent’ has not been declared
   33 |     void OnTimer(wxTimerEvent &event);
      |                  ^~~~~~~~~~~~

(cherry picked from commit b890f0a39fcb48a1f1e1ee01f2aacf5d2fa35ad6)