FIX: Fix missing FilamentMapMode declaration
/run/build/BambuStudio/src/slic3r/GUI/3DScene.hpp: At global scope:
/run/build/BambuStudio/src/slic3r/GUI/3DScene.hpp:65:5: error: ‘FilamentMapMode’ does not name a type
   65 |     FilamentMapMode         mode;
      |     ^~~~~~~~~~~~~~~

(cherry picked from commit eaec4c997eca8310e9037b70567dceed79dd210c)