FIX: Fix missing wxTimer declaration
src/slic3r/GUI/DeviceCore/DevManager.h:108:5: error: ‘wxTimer’ does not name a type
  108 |     wxTimer* m_timer{ nullptr };
      |     ^~~~~~~

(cherry picked from commit be709a977ea47380135606cccfab325cc5bb9df1)