FIX: Fix missing boost::lexical_cast declaration
/run/build/BambuStudio/src/slic3r/GUI/PartSkipDialog.cpp: In lambda function:
/run/build/BambuStudio/src/slic3r/GUI/PartSkipDialog.cpp:495: error: ‘lexical_cast’ is not a member of ‘boost’
  495 |                     url += "&refresh_url=" + boost::lexical_cast<std::string>(&refresh_agora_url);

(cherry picked from commit fc8537c038a8dcc419f8b5558feb71700b77c996)