FIX: Fix missing BOOST_LOG_TRIVIAL() declaration
/run/build/BambuStudio/src/slic3r/GUI/SkipPartCanvas.cpp: In member function ‘void Slic3r::GUI::_BBS_3MF_Base::log_errors()’:
/run/build/BambuStudio/src/slic3r/GUI/SkipPartCanvas.cpp:598:47: error: ‘BOOST_LOG_TRIVIAL’ was not declared in this scope
  598 |     for (const std::string &error : m_errors) BOOST_LOG_TRIVIAL(error) << error;
      |                                               ^~~~~~~~~~~~~~~~~

(cherry picked from commit dba7f3ad07f530ddce3e75eaf8f357794cfd1935)