FIX: Fix missing BOOST_LOG_TRIVIAL declaration
src/slic3r/GUI/Widgets/../DeviceCore/DevConfigUtil.h:100:91: error: ‘BOOST_LOG_TRIVIAL’ was not declared in this scope
  100 |         catch (...) { assert(0 && "get_value_from_config failed"); BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << " failed"; }// there are file errors
      |                                                                                           ^

(cherry picked from commit 11d17a60104a28d7d51024d861227fb98b4709e4)